name: Build and Release spiffe-proxy

on:
  create:
    tags:
      - 'spiffe-proxy-v*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.21.x'
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: ko-build/setup-ko@ace48d793556083a76f1e3e6068850c1f4a369aa # v0.6
      - name: Extract short tag from the tag name
        run: echo "SHORT_TAG=${GITHUB_REF#refs/tags/spiffe-proxy-}" >> $GITHUB_ENV
      - run: |
          cd spiffe-proxy
          ko build . --base-import-paths --tags ${{ env.SHORT_TAG }} --tag-only --platform linux/arm64,linux/amd64